name: detekt

on: workflow_call

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Setup detekt"
        uses: peter-murray/setup-detekt@v3

      - name: "Run detekt"
        run: detekt-cli --config "config/detekt.yml" --excludes "**/*Test/**,**/*.kts"
